url: https://blog.hirokuma.work
lang: ja-JP
source: .
plugins:
  - jekyll-remote-theme
  - jekyll-last-modified-at
  - jekyll-redirect-from
title: hiro99ma blog
description: 何か技術的なこと
google_analytics: G-552KB5LZK4
show_downloads: false
theme: jekyll-theme-hacker
