url: https://blog.hirokuma.work
lang: ja-JP
source: .
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
title: hiro99ma blog
google_analytics: G-552KB5LZK4
show_downloads: false
theme: jekyll-theme-hacker
author: hiro99ma
collections:
  tags:
    output: true
